Update patch set 5
Patch Set 5:

(5 comments)

ok locally I am now seeing the tox build as a success.. I received a congratulations from tox :) but not sure why LF jenkins build is failing

ERROR:   py35: could not install deps [-rtesting/tox-requirements.txt]; v = InvocationError('/w/workspace/python-model-runner-pypi-verify-master/.tox/py35/bin/python -m pip install -rtesting/tox-requirements.txt', 1)
  py36: commands succeeded
  flake8: commands succeeded

From the dependency tree on zipp.. I see this graph

pipdeptree --reverse --packages zipp
zipp==2.0.0
  - importlib-metadata==1.4.0 [requires: zipp>=0.5]
    - jsonschema==3.2.0 [requires: importlib-metadata]
      - connexion==1.5.3 [requires: jsonschema>=2.5.1]
        - acumos-model-runner==0.2.3 [requires: connexion<2.0.0]
      - swagger-spec-validator==2.4.3 [requires: jsonschema]
        - connexion==1.5.3 [requires: swagger-spec-validator>=2.3.1]
          - acumos-model-runner==0.2.3 [requires: connexion<2.0.0]
    - pluggy==0.13.1 [requires: importlib-metadata>=0.12]
      - pytest==5.3.4 [requires: pluggy>=0.12,<1.0]
        - pytest-cov==2.8.1 [requires: pytest>=3.6]
      - tox==3.14.3 [requires: pluggy>=0.12.0,<1]
        - tox-pyenv==1.1.0 [requires: tox>=2.0]
    - pytest==5.3.4 [requires: importlib-metadata>=0.12]
      - pytest-cov==2.8.1 [requires: pytest>=3.6]
    - tox==3.14.3 [requires: importlib-metadata>=0.12,<2]
      - tox-pyenv==1.1.0 [requires: tox>=2.0]

From the zipp 2.0.0 page they declare only supporting 3.6 and above. On my local machine I am seeing zipp 1.0.0 installed not 2.0.0 ... that appears to be the difference between local and jenkins. 

Local py35 tox build is showing zipp 1.0.0 

py35 installed: acumos==0.9.1,acumos-model-runner==0.2.3,appdirs==1.4.3,attrs==19.3.0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,clickclick==1.2.2,connexion==1.5.3,coverage==5.0.3,dill==0.3.1.1,filelock==3.0.12,Flask==1.1.1,Flask-Cors==3.0.8,gunicorn==20.0.4,idna==2.8,importlib-metadata==1.4.0,inflection==0.3.1,itsdangerous==1.1.0,Jinja2==2.10.3,jsonschema==3.2.0,lark-parser==0.7.8,MarkupSafe==1.1.1,more-itertools==8.1.0,numpy==1.18.1,packaging==20.0,pathlib2==2.3.5,pexpect==4.8.0,pluggy==0.13.1,protobuf==3.11.2,ptyprocess==0.6.0,py==1.8.1,pyparsing==2.4.6,pyrsistent==0.15.7,pytest==5.3.4,pytest-cov==2.8.1,PyYAML==5.3,requests==2.22.0,six==1.14.0,swagger-spec-validator==2.4.3,swagger-ui-bundle==0.0.6,typing==3.7.4.1,urllib3==1.25.8,wcwidth==0.1.8,Werkzeug==0.16.0,zipp==1.0.0

This is strange and I am not sure how to resolve. Any suggesstions? Maybe it is a difference in tox version maybe that is different version .. I am running tox 3.14.3 locally running under python 3.7. Maybe this version of tox takes into consideration the max python version.

Patch-set: 5